import fs from 'node:fs';
import path from 'node:path';
import { ROOT, buildSearchIndex, loadContent, validateContent } from './lib/content.mjs';
const content = loadContent();
const validation = validateContent(content);
if (validation.errors.length) throw new Error(validation.errors.join('\n'));
const bundle = {
  schemaVersion: 1,
  contentVersion: '2026.09.04',
  ...content,
  searchIndex: buildSearchIndex(content.substances),
  ambiguousAliases: validation.ambiguousAliases,
};
const json = JSON.stringify(bundle, null, 2) + '\n';
fs.mkdirSync(path.join(ROOT, 'generated'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'generated/content.json'), json);
fs.writeFileSync(
  path.join(ROOT, 'generated/content.ts'),
  `/* Generated by npm run generate. Do not edit. */\nimport data from './content.json';\nexport default data;\n`,
);
console.log('Generated deterministic content bundle.');
