import fs from 'node:fs';
import path from 'node:path';
import { ROOT, buildContentBundle, loadContent, serializeContentBundle } from './lib/content.mjs';

const json = serializeContentBundle(buildContentBundle(loadContent()));
fs.mkdirSync(path.join(ROOT, 'generated'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'generated/content.json'), json);
fs.writeFileSync(
  path.join(ROOT, 'generated/content.ts'),
  `/* Generated by npm run generate. Do not edit. */\nimport data from './content.json';\nexport default data;\n`,
);
console.log('Generated deterministic content bundle.');
