import fs from 'node:fs';
import path from 'node:path';
import {
  ROOT,
  buildContentBundle,
  buildEmergencyBundle,
  loadContent,
  serializeContentBundle,
} from './lib/content.mjs';

const bundle = buildContentBundle(loadContent());
const json = serializeContentBundle(bundle);
fs.mkdirSync(path.join(ROOT, 'generated'), { recursive: true });
fs.writeFileSync(path.join(ROOT, 'generated/content.json'), json);
fs.writeFileSync(path.join(ROOT, 'generated/sources.json'), serializeContentBundle(bundle.sources));
fs.writeFileSync(
  path.join(ROOT, 'generated/emergency.json'),
  serializeContentBundle(buildEmergencyBundle(bundle)),
);
fs.writeFileSync(
  path.join(ROOT, 'generated/content.ts'),
  `/* Generated by npm run generate. Do not edit. */\nimport data from './content.json';\nexport default data;\n`,
);
console.log('Generated deterministic content bundle.');
